### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by hackingbobcat** [jtgilbert/VBET-2#21]
Received a NotImplementedError when running latest Win64 VBET-2 executable as well as from source:

ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
  if self.network.loc[i].geometry.type == 'MultiLineString':
Traceback (most recent call last):
  File "C:\Users\ericl\miniconda3\envs\vbet\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\ericl\miniconda3\envs\vbet\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\ericl\projects\GIS\klickitat\hydrology\VBET\VBET-2-master\run_VBET.py", line 35, in <module>
    vbrun.run()
  File "C:\Users\ericl\projects\GIS\klickitat\hydrology\VBET\VBET-2-master\run_VBET.py", line 28, in run
    vb = classVBET.VBET(**self.params)
  File "C:\Users\ericl\projects\GIS\klickitat\hydrology\VBET\VBET-2-master\classVBET.py", line 128, in __init__
    if len(self.network.loc[i].geometry.xy[0]) <= 5:
  File "C:\Users\ericl\miniconda3\envs\vbet\lib\site-packages\shapely\geometry\base.py", line 229, in xy
    raise NotImplementedError
NotImplementedError

Package list from my environment is attached.
[VBET Environment.pdf](https://github.com/jtgilbert/VBET-2/files/13826887/VBET.Environment.pdf)

**Comment by drewbartshire** [comment]
I had a similar error the first time I ran the tool. The issue for me was that I had a few very small line segments at the end of a stream that didn't have 5 vertices because they were just small little scraps. I ordered my table by shapelength and deleted all lines that were clearly just short scraps.

**Comment by hackingbobcat** [comment]
Thanks for the guidance.  I will check my data and see if that solves it.
