### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by wwicherski** [jtgilbert/VBET-2#7]
I am getting the following error when I try and run VBET-2 for an area around Pagosa Springs, CO.  

vb.valley_bottom()
segment  1  of  51
Traceback (most recent call last):

  File "<ipython-input-59-a7ebebb8bd83>", line 1, in <module>
    vb.valley_bottom()

  File "G:\Shared drives\Projects\xxxxx\Data\GIS\elevation\VBET-2-master\VBET.py", line 372, in valley_bottom
    detr = self.detrend(dem, geom)  # might want to change this offset

  File "G:\Shared drives\Projects\xxxxx\Data\GIS\elevation\VBET-2-master\VBET.py", line 147, in detrend
    xs[i] = int((_xs[i] - x_min) / res_x)  # column in array space

ZeroDivisionError: float division by zero

**Comment by wwicherski** [comment]
The answer is to change the indexed values of the transform array.  Currently it is using the minimum x and y values as the dem resolution values...
